[package]
name = "off_chain_signature"
version = "0.2.0"

[[target.starknet-contract]]
sierra = true

[dependencies]
starknet = "=2.2.0"

[scripts]
SimpleStruct= "npx ts-node scripts/SimpleStruct.ts"
StructWithArray= "npx ts-node scripts/StructWithArray.ts"
StructWithEnum= "npx ts-node scripts/StructWithEnum.ts"
StructWithComplexEnum= "npx ts-node scripts/StructWithComplexEnum.ts"
StructWithTuple= "npx ts-node scripts/StructWithTuple.ts"
StructWithU256= "npx ts-node scripts/StructWithU256.ts"
format = "scarb fmt && npx prettier --write ."