[package]
name = "off_chain_signature"
version = "0.3.0"

[[target.starknet-contract]]
sierra = true

[dependencies]
starknet = "2.8.2"

[dev-dependencies]
cairo_test = "2.8.2"

[scripts]
SimpleStruct = "npx ts-node scripts/v0/SimpleStruct.ts"
SimpleStructV1 = "npx ts-node scripts/v1/SimpleStruct.ts"
StructWithArray = "npx ts-node scripts/v0/StructWithArray.ts"
StructWithArrayV1 = "npx ts-node scripts/v1/StructWithArray.ts"
StructWithMerkletree = "npx ts-node scripts/v0/StructWithMerkletree.ts"
StructWithMerkletreeV1 = "npx ts-node scripts/v1/StructWithMerkletree.ts"
StructWithU256 = "npx ts-node scripts/v0/StructWithU256.ts"
StructWithU256V1 = "npx ts-node scripts/v1/StructWithU256.ts"
StructWithByteArray = "npx ts-node scripts/v1/StructWithByteArray.ts"
format = "scarb fmt && npx prettier --write ."

## TODO ADD ALL STANDARD INTERFACES